### ISSUE TITLE
Sign FParsec-Pipes with a strong name

### ISSUE THREAD

**Issue by chkimes** [rspeele/FParsec-Pipes#4]
Users of my library graphql-net are attempting to deploy to SharePoint and having troubles because FParsec-Pipes is not signed on NuGet:

https://github.com/ckimes89/graphql-net/issues/69

**Comment by rspeele** [comment]
Check out [0.3.1](https://www.nuget.org/packages/FParsec-Pipes/0.3.1).
This release features an improved name (up to 60% stronger) that won't bend or shatter under the strain of running in Sharepoint.
