### ISSUE TITLE
Support .NET Standard 2.0

### ISSUE THREAD

**Issue by MarianPalkus** [rspeele/FParsec-Pipes#7]
Hi,
is it possible to support .NET Standard 2.0?
The project graphql-net depends on this library, i try to add support for .NET Standard 2.0 (see https://github.com/ckimes89/graphql-net/issues/34).

Started a PR as well: https://github.com/rspeele/FParsec-Pipes/pull/6

**Comment by thangchung** [comment]
+1

**Comment by devtestr** [comment]
+1

**Comment by vertonghenb** [comment]
+1

**Comment by rspeele** [comment]
Bit late but the support is there now.
